---
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: stivesalive.co.uk
url: https://stivesalive.co.uk
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:title/"
twitter_username: jekyllrb
github_username:  jekyll
host: localhost
collections:
  campaigns:
    title: Campaigns
    output: true
    permalink: "/:collection/:title/"
  uploads:
    title: Uploads
    output: true
sass:
  style: "compressed"

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - bin
  - config
  - tmp
  - Procfile.dev
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
